"""
ACE Pattern Context System - Bullet-based knowledge management.

Implements the Agentic Context Engineering pattern with:
- ContextBullet: Individual knowledge entries with metadata
- AgentPlaybook: Semantic retrieval and grow-and-refine deduplication
- Rubric-based scoring for quality assessment
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Dict, Any, Optional, Tuple
import numpy as np
from sentence_transformers import SentenceTransformer
from sqlalchemy import Column, String, Text, DateTime, JSON, Float, Integer, ARRAY, text
from sqlalchemy.dialects.postgresql import JSONB
from pgvector.sqlalchemy import Vector
from .database import Base
import logging

logger = logging.getLogger(__name__)

# Shared SentenceTransformer instance (memory leak prevention)
# Each model instance uses ~90MB - sharing avoids per-user duplication
_shared_embedder: Optional[SentenceTransformer] = None
_shared_embedder_model: Optional[str] = None


def _get_shared_embedder(model_name: str = "all-MiniLM-L6-v2") -> SentenceTransformer:
    """Get or create a shared SentenceTransformer.

    Prevents loading duplicate ~90MB models per user playbook.
    Force CPU to avoid GPU memory contention with training.
    """
    global _shared_embedder, _shared_embedder_model
    if _shared_embedder is None or _shared_embedder_model != model_name:
        logger.info(f"Loading shared embedder model: {model_name}")
        _shared_embedder = SentenceTransformer(model_name, device="cpu")
        _shared_embedder_model = model_name
    return _shared_embedder


@dataclass
class ContextBullet:
    """Single knowledge entry with ACE pattern metadata.

    Represents atomic knowledge that can be:
    - Generated by the agent (actions, plans)
    - Reflected upon (critiques, analyses)
    - Curated (lessons learned, patterns)
    - From tool results (execution outputs)
    - From user feedback (corrections, preferences)
    """

    id: str
    content: str  # The actual knowledge
    category: str  # generator, reflector, curator, tool_result, user_feedback
    source: str  # Which agent/tool/user created this
    timestamp: datetime
    embedding: np.ndarray

    # ACE metadata - track utility over time
    helpful_count: int = 0
    harmful_count: int = 0
    relevance_score: float = 0.0

    # Kimi K2-style rubric scores (0-1 scale)
    rubric_scores: Dict[str, float] = field(default_factory=dict)
    # Common rubrics: clarity, accuracy, safety, actionability, importance

    # Session context
    session_id: Optional[str] = None
    user_id: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for storage."""
        return {
            "id": self.id,
            "content": self.content,
            "category": self.category,
            "source": self.source,
            "timestamp": self.timestamp.isoformat(),
            "embedding": self.embedding.tolist(),
            "helpful_count": self.helpful_count,
            "harmful_count": self.harmful_count,
            "relevance_score": self.relevance_score,
            "rubric_scores": self.rubric_scores,
            "session_id": self.session_id,
            "user_id": self.user_id,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ContextBullet":
        """Create from dictionary."""
        return cls(
            id=data["id"],
            content=data["content"],
            category=data["category"],
            source=data["source"],
            timestamp=datetime.fromisoformat(data["timestamp"]),
            embedding=np.array(data["embedding"]),
            helpful_count=data.get("helpful_count", 0),
            harmful_count=data.get("harmful_count", 0),
            relevance_score=data.get("relevance_score", 0.0),
            rubric_scores=data.get("rubric_scores", {}),
            session_id=data.get("session_id"),
            user_id=data.get("user_id"),
        )

    def get_utility_score(self) -> float:
        """Calculate utility score based on helpful/harmful feedback."""
        total = self.helpful_count + self.harmful_count
        if total == 0:
            return 0.5  # Neutral for new bullets
        return self.helpful_count / total

    def get_average_rubric_score(self) -> float:
        """Calculate average of all rubric scores."""
        if not self.rubric_scores:
            return 0.5
        return sum(self.rubric_scores.values()) / len(self.rubric_scores)


class PlaybookBullet(Base):
    """SQLAlchemy model for persistent storage of context bullets."""

    __tablename__ = "playbook_bullets"

    id = Column(String, primary_key=True)
    user_id = Column(String, index=True)
    session_id = Column(String, index=True, nullable=True)

    content = Column(Text, nullable=False)
    category = Column(
        String, index=True
    )  # generator, reflector, curator, tool_result, user_feedback
    source = Column(String)
    timestamp = Column(DateTime, default=datetime.now, index=True)

    # ACE metadata
    helpful_count = Column(Integer, default=0)
    harmful_count = Column(Integer, default=0)
    relevance_score = Column(Float, default=0.0)

    # Rubric scores stored as JSONB; embedding stored as pgvector for ANN queries
    rubric_scores = Column(JSONB)
    embedding = Column(Vector(384))  # pgvector HNSW index (see Alembic migration)

    def to_context_bullet(self) -> ContextBullet:
        """Convert to ContextBullet dataclass."""
        return ContextBullet(
            id=self.id,
            content=self.content,
            category=self.category,
            source=self.source,
            timestamp=self.timestamp,
            embedding=np.array(self.embedding),
            helpful_count=self.helpful_count,
            harmful_count=self.harmful_count,
            relevance_score=self.relevance_score,
            rubric_scores=self.rubric_scores or {},
            session_id=self.session_id,
            user_id=self.user_id,
        )


class AgentPlaybook:
    """Structured knowledge base using ACE pattern.

    Features:
    - Semantic retrieval using sentence embeddings
    - Grow-and-refine: automatic deduplication when max size exceeded
    - Category-based filtering (generator, reflector, curator, etc.)
    - Utility-weighted ranking (helpful/harmful feedback)
    """

    def __init__(
        self,
        user_id: str,
        embedder_model: str = "all-MiniLM-L6-v2",
        max_bullets: int = 1000,
        dedup_threshold: float = 0.95,  # Cosine similarity threshold
    ):
        self.user_id = user_id
        self.max_bullets = max_bullets
        self.dedup_threshold = dedup_threshold

        # Use shared sentence transformer (avoids ~90MB duplicate per user)
        self.embedder = _get_shared_embedder(embedder_model)

        # In-memory cache of bullets (loaded from DB on init)
        self.bullets: List[ContextBullet] = []

    def add_bullet(
        self,
        content: str,
        category: str,
        source: str,
        session_id: Optional[str] = None,
        rubric_scores: Optional[Dict[str, float]] = None,
    ) -> ContextBullet:
        """Add new knowledge bullet with incremental delta update.

        Args:
            content: The knowledge content
            category: generator, reflector, curator, tool_result, user_feedback
            source: Origin of the knowledge (e.g., "agent", "user", "github_tool")
            session_id: Current session ID for tracking
            rubric_scores: Optional quality scores (clarity, accuracy, etc.)

        Returns:
            The created ContextBullet
        """
        # Generate embedding
        embedding = self.embedder.encode(content)

        # Create bullet
        bullet = ContextBullet(
            id=f"{category}_{self.user_id}_{len(self.bullets)}",
            content=content,
            category=category,
            source=source,
            timestamp=datetime.now(),
            embedding=embedding,
            rubric_scores=rubric_scores or {},
            session_id=session_id,
            user_id=self.user_id,
        )

        self.bullets.append(bullet)
        logger.info(f"Added bullet {bullet.id} (category={category}, source={source})")

        # Grow-and-refine: deduplicate if exceeded max
        if len(self.bullets) > self.max_bullets:
            logger.info(
                f"Playbook size {len(self.bullets)} exceeds max {self.max_bullets}, deduplicating..."
            )
            self._deduplicate()

        return bullet

    def retrieve_relevant(
        self,
        query: str,
        top_k: int = 10,
        category: Optional[str] = None,
        min_utility: float = 0.0,
    ) -> List[ContextBullet]:
        """Semantic retrieval using cosine similarity.

        Args:
            query: The query text to find relevant bullets
            top_k: Number of bullets to return
            category: Optional filter by category
            min_utility: Minimum utility score (helpful/harmful ratio)

        Returns:
            List of most relevant ContextBullets
        """
        if not self.bullets:
            return []

        # Generate query embedding
        query_emb = self.embedder.encode(query)

        # Filter candidates
        candidates = self.bullets
        if category:
            candidates = [b for b in candidates if b.category == category]
        if min_utility > 0:
            candidates = [b for b in candidates if b.get_utility_score() >= min_utility]

        if not candidates:
            return []

        # Calculate cosine similarities
        similarities: List[Tuple[ContextBullet, float]] = []
        for bullet in candidates:
            cosine_sim = np.dot(query_emb, bullet.embedding) / (
                np.linalg.norm(query_emb) * np.linalg.norm(bullet.embedding)
            )
            similarities.append((bullet, cosine_sim))

        # Sort by similarity, then by utility score
        similarities.sort(key=lambda x: (x[1], x[0].get_utility_score()), reverse=True)

        top_bullets = [b for b, _ in similarities[:top_k]]
        logger.info(
            f"Retrieved {len(top_bullets)} relevant bullets for query (category={category})"
        )

        return top_bullets

    def update_feedback(self, bullet_id: str, helpful: bool):
        """Update helpful/harmful counts based on feedback.

        Args:
            bullet_id: ID of the bullet to update
            helpful: True if helpful, False if harmful
        """
        for bullet in self.bullets:
            if bullet.id == bullet_id:
                if helpful:
                    bullet.helpful_count += 1
                else:
                    bullet.harmful_count += 1
                logger.info(
                    f"Updated feedback for {bullet_id}: helpful={bullet.helpful_count}, harmful={bullet.harmful_count}"
                )
                return

        logger.warning(f"Bullet {bullet_id} not found for feedback update")

    def _deduplicate(self):
        """Semantic deduplication using ACE grow-and-refine pattern.

        Strategy:
        1. Keep high-utility bullets (helpful_count > harmful_count)
        2. Remove semantically similar bullets with lower utility
        3. Always keep recent curator bullets (important lessons)
        """
        if len(self.bullets) <= self.max_bullets:
            return

        # Separate bullets by category
        curator_bullets = [b for b in self.bullets if b.category == "curator"]
        other_bullets = [b for b in self.bullets if b.category != "curator"]

        # Always keep recent curator bullets (last 100)
        recent_curators = sorted(
            curator_bullets, key=lambda b: b.timestamp, reverse=True
        )[:100]

        # Sort other bullets by utility score
        other_bullets.sort(key=lambda b: b.get_utility_score(), reverse=True)

        # Deduplicate other bullets
        deduplicated = []
        for bullet in other_bullets:
            # Check similarity with existing deduplicated bullets
            is_duplicate = False
            for existing in deduplicated:
                cosine_sim = np.dot(bullet.embedding, existing.embedding) / (
                    np.linalg.norm(bullet.embedding)
                    * np.linalg.norm(existing.embedding)
                )
                if cosine_sim >= self.dedup_threshold:
                    # Keep the one with higher utility
                    if bullet.get_utility_score() > existing.get_utility_score():
                        deduplicated.remove(existing)
                        deduplicated.append(bullet)
                    is_duplicate = True
                    break

            if not is_duplicate:
                deduplicated.append(bullet)

        # Combine and limit to max_bullets
        target_size = self.max_bullets - len(recent_curators)
        self.bullets = recent_curators + deduplicated[:target_size]

        logger.info(
            f"Deduplicated playbook: {len(recent_curators)} curators + {len(deduplicated[:target_size])} others = {len(self.bullets)} total"
        )

    def get_summary(self) -> Dict[str, Any]:
        """Get playbook statistics."""
        category_counts = {}
        for bullet in self.bullets:
            category_counts[bullet.category] = (
                category_counts.get(bullet.category, 0) + 1
            )

        return {
            "user_id": self.user_id,
            "total_bullets": len(self.bullets),
            "max_bullets": self.max_bullets,
            "category_counts": category_counts,
            "avg_utility_score": (
                np.mean([b.get_utility_score() for b in self.bullets])
                if self.bullets
                else 0.0
            ),
        }

    def to_context_string(self, bullets: List[ContextBullet]) -> str:
        """Format bullets as context string for LLM prompts."""
        if not bullets:
            return "No relevant context found."

        lines = []
        for bullet in bullets:
            utility = bullet.get_utility_score()
            avg_rubric = bullet.get_average_rubric_score()
            lines.append(
                f"- [{bullet.category}] {bullet.content} "
                f"(utility: {utility:.2f}, quality: {avg_rubric:.2f})"
            )

        return "\n".join(lines)

    def build_tiered_context(
        self,
        query: str,
        session_id: Optional[str] = None,
        budget_chars: int = 12000,
        recent_k: int = 6,
        semantic_k: int = 8,
        curator_k: int = 4,
        min_utility: float = 0.3,
    ) -> Dict[str, Any]:
        """Build 3-tier context for prompt construction.

        Tiers:
        1) Recent session memory (short-term continuity)
        2) Semantic retrieval for current query (task relevance)
        3) Curator lessons with high utility (long-term memory)
        """
        selected_ids = set()
        section_lines: List[str] = []
        used_chars = 0
        dropped_count = 0

        def append_line(line: str) -> bool:
            nonlocal used_chars, dropped_count
            line_len = len(line) + 1
            if used_chars + line_len > budget_chars:
                dropped_count += 1
                return False
            section_lines.append(line)
            used_chars += line_len
            return True

        def append_tier(title: str, bullets: List[ContextBullet]) -> int:
            if not bullets:
                return 0

            kept = 0
            if append_line(title):
                for bullet in bullets:
                    utility = bullet.get_utility_score()
                    avg_rubric = bullet.get_average_rubric_score()
                    content = bullet.content.strip().replace("\n", " ")
                    line = (
                        f"- [{bullet.category}] {content} "
                        f"(utility: {utility:.2f}, quality: {avg_rubric:.2f})"
                    )
                    if append_line(line):
                        selected_ids.add(bullet.id)
                        kept += 1
                append_line("")
            return kept

        # Tier 1: recent same-session bullets
        tier1_recent: List[ContextBullet] = []
        if session_id:
            tier1_recent = sorted(
                [b for b in self.bullets if b.session_id == session_id],
                key=lambda b: b.timestamp,
                reverse=True,
            )[:recent_k]
            tier1_recent.reverse()  # preserve chronological order

        # Tier 2: semantic retrieval
        tier2_semantic = self.retrieve_relevant(
            query=query,
            top_k=semantic_k,
            min_utility=min_utility,
        )
        tier2_semantic = [b for b in tier2_semantic if b.id not in selected_ids]

        # Tier 3: high-utility curator lessons
        tier3_curator = sorted(
            [
                b
                for b in self.bullets
                if b.category == "curator"
                and b.get_utility_score() >= min_utility
                and b.id not in selected_ids
            ],
            key=lambda b: (b.get_utility_score(), b.timestamp),
            reverse=True,
        )[:curator_k]

        tier1_kept = append_tier("## Tier 1 — Session Memory", tier1_recent)
        tier2_semantic = [b for b in tier2_semantic if b.id not in selected_ids]
        tier2_kept = append_tier("## Tier 2 — Relevant Knowledge", tier2_semantic)
        tier3_curator = [b for b in tier3_curator if b.id not in selected_ids]
        tier3_kept = append_tier("## Tier 3 — Long-term Lessons", tier3_curator)

        if not section_lines:
            context_text = "No relevant context found."
        else:
            context_text = "\n".join(section_lines).rstrip()

        return {
            "context": context_text,
            "tiers": {
                "tier1_session": tier1_kept,
                "tier2_semantic": tier2_kept,
                "tier3_curator": tier3_kept,
            },
            "total_bullets": tier1_kept + tier2_kept + tier3_kept,
            "used_chars": used_chars,
            "budget_chars": budget_chars,
            "dropped_count": dropped_count,
        }


# Persistence functions for PostgreSQL integration


async def save_playbook_to_db(db_session, playbook: AgentPlaybook):
    """Persist all bullets to PostgreSQL."""
    for bullet in playbook.bullets:
        db_bullet = PlaybookBullet(
            id=bullet.id,
            user_id=bullet.user_id,
            session_id=bullet.session_id,
            content=bullet.content,
            category=bullet.category,
            source=bullet.source,
            timestamp=bullet.timestamp,
            helpful_count=bullet.helpful_count,
            harmful_count=bullet.harmful_count,
            relevance_score=bullet.relevance_score,
            rubric_scores=bullet.rubric_scores,
            embedding=bullet.embedding.tolist(),
        )
        await db_session.merge(db_bullet)  # Insert or update

    await db_session.commit()
    logger.info(
        f"Saved {len(playbook.bullets)} bullets to database for user {playbook.user_id}"
    )


async def load_playbook_from_db(db_session, user_id: str) -> AgentPlaybook:
    """Load playbook from PostgreSQL."""
    from sqlalchemy import select

    playbook = AgentPlaybook(user_id=user_id)

    # Query bullets for user using proper SQLAlchemy query
    query = (
        select(PlaybookBullet)
        .where(PlaybookBullet.user_id == user_id)
        .order_by(PlaybookBullet.timestamp.desc())
        .limit(playbook.max_bullets)
    )

    result = await db_session.execute(query)
    db_bullets = result.scalars().all()

    playbook.bullets = [bullet.to_context_bullet() for bullet in db_bullets]
    logger.info(
        f"Loaded {len(playbook.bullets)} bullets from database for user {user_id}"
    )

    return playbook


async def retrieve_ann_from_db(
    db_session,
    user_id: str,
    query_embedding: "np.ndarray",
    top_k: int = 20,
    category: Optional[str] = None,
) -> List["ContextBullet"]:
    """ANN retrieval using pgvector HNSW <=> cosine-distance operator.

    Replaces the O(n) in-memory numpy cosine scan for large playbooks.
    Requires the HNSW index created by the Alembic migration:
        CREATE INDEX ON playbook_bullets USING hnsw (embedding vector_cosine_ops)

    Args:
        db_session: Async SQLAlchemy session
        user_id: Filter bullets to this user
        query_embedding: 384-dim float32 vector from SentenceTransformer
        top_k: Number of nearest neighbours to return
        category: Optional category filter

    Returns:
        List of ContextBullet ordered by cosine similarity (closest first)
    """
    from sqlalchemy import select

    vec_literal = query_embedding.tolist()

    stmt = (
        select(PlaybookBullet)
        .where(PlaybookBullet.user_id == user_id)
    )
    if category:
        stmt = stmt.where(PlaybookBullet.category == category)

    # pgvector cosine-distance operator <=> (lower = more similar)
    stmt = stmt.order_by(
        PlaybookBullet.embedding.cosine_distance(vec_literal)
    ).limit(top_k)

    result = await db_session.execute(stmt)
    db_bullets = result.scalars().all()
    return [b.to_context_bullet() for b in db_bullets]

